# Generated by Django 5.0.4 on 2024-05-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0002_rename_number_cardb_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardb',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
