# Generated by Django 5.0.4 on 2024-05-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0003_alter_cardb_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbrand', models.CharField(blank=True, max_length=100, null=True)),
                ('bname', models.CharField(blank=True, max_length=100, null=True)),
                ('bmodel', models.CharField(blank=True, max_length=100, null=True)),
                ('bprice', models.IntegerField(blank=True, null=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='Brand image')),
            ],
        ),
    ]
