# Generated by Django 5.0.4 on 2024-05-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0004_branddb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branddb',
            old_name='pimage',
            new_name='bimage',
        ),
    ]
