# Generated by Django 5.0.4 on 2024-05-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0005_rename_pimage_branddb_bimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branddb',
            name='bmodel',
        ),
        migrations.RemoveField(
            model_name='branddb',
            name='bname',
        ),
        migrations.RemoveField(
            model_name='branddb',
            name='bprice',
        ),
        migrations.AddField(
            model_name='branddb',
            name='bdescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
