# Generated by Django 5.0.4 on 2024-08-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0007_cardb_gst_cardb_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1', models.CharField(blank=True, max_length=100, null=True)),
                ('Option1', models.CharField(blank=True, max_length=100, null=True)),
                ('Option2', models.CharField(blank=True, max_length=100, null=True)),
                ('Option3', models.CharField(blank=True, max_length=100, null=True)),
                ('Option4', models.CharField(blank=True, max_length=100, null=True)),
                ('Option5', models.CharField(blank=True, max_length=100, null=True)),
                ('feature2', models.CharField(blank=True, max_length=100, null=True)),
                ('Option6', models.CharField(blank=True, max_length=100, null=True)),
                ('Option7', models.CharField(blank=True, max_length=100, null=True)),
                ('Option8', models.CharField(blank=True, max_length=100, null=True)),
                ('Option9', models.CharField(blank=True, max_length=100, null=True)),
                ('Option10', models.CharField(blank=True, max_length=100, null=True)),
                ('feature3', models.CharField(blank=True, max_length=100, null=True)),
                ('Option11', models.CharField(blank=True, max_length=100, null=True)),
                ('Option12', models.CharField(blank=True, max_length=100, null=True)),
                ('Option13', models.CharField(blank=True, max_length=100, null=True)),
                ('Option14', models.CharField(blank=True, max_length=100, null=True)),
                ('Option15', models.CharField(blank=True, max_length=100, null=True)),
                ('feature4', models.CharField(blank=True, max_length=100, null=True)),
                ('Option16', models.CharField(blank=True, max_length=100, null=True)),
                ('Option17', models.CharField(blank=True, max_length=100, null=True)),
                ('Option18', models.CharField(blank=True, max_length=100, null=True)),
                ('Option19', models.CharField(blank=True, max_length=100, null=True)),
                ('Option20', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('option5', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
