# Generated by Django 5.0.4 on 2024-08-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0008_featuredb_specificationsdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredb',
            old_name='Option10',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option11',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option12',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option13',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option14',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option15',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option16',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option17',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option18',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option19',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option20',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option6',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option7',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option8',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='Option9',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='feature1',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='feature2',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='feature3',
        ),
        migrations.RemoveField(
            model_name='featuredb',
            name='feature4',
        ),
    ]
